@startuml

javajfx.org.Application <-- Main
Main -- MainWindowController
MainWindowController -- EditItems
MainWindowController -- SortItems
MainWindowController -- SearchItem
MainWindowController -- FileOptions

class Main{
    main()
    start()
}

class MainWindowController{
    nameTextField: TextField;
    sNumberTextField: TextField;
    valueTextField: TextField;
    searchDisplay: TextField;
    itemsTableView: TableView;
    itemsValueColumn: TableColumn;
    itemsSNumberColumn: TableColumn;
    itemsNameColumn: TableColumn;
    menuBar: MenuBar;
    fileOption: Menu;
    helpOption: Menu;
    openMenuItem: Menuitem;
    saveAsMenuItem: MenuItem;


    searchButtonClicked(actionEvent)
    addItemButtonClicked(actionEvent)
    deleteItemButtonClicked(actionEvent)
    fileMenuButtonCLicked()
    helpMenuButtonClicked()
}

class EditItems {
    addNewItem()
    removeItem()
    editValue()
    editName()
    editSerialNumber()
}

class SortItems{
    sortByValue()
    sortByName()
    sortBySerialNumber()
}

class SearchItem{
    searchByValue()
    searchByName()
    searchBySerialNumber()
}

class FileOptions{
    saveFile()
    saveAsTSV()
    saveAsHTML()
    saveAsJSON()
    openFile()
}


@enduml