@startuml

javafx.org.Application <-- Main
Main -- MainWindowController
MainWindowController -- EditItems
MainWindowController -- SortItems
MainWindowController -- SearchItem
MainWindowController -- FileOptions
MainWindowController -- AddItems

class Main{
    main()
    start()
}

class MainWindowController{
    nameTextField: TextField
    sNumberTextField: TextField
    valueTextField: TextField
    searchDisplay: TextField
    itemsTableView: TableView
    itemsValueColumn: TableColumn
    itemsSNumberColumn: TableColumn
    itemsNameColumn: TableColumn
    menuBar: MenuBar
    fileOption: Menu
    helpOption: Menu
    openMenuItem: MenuItem
    saveAsMenuItem: MenuItem
    aboutMenuItem: MenuItem
    fOption: FileOptions

    searchButtonClicked(actionEvent)
    addItemButtonClicked(actionEvent)
    deleteItemButtonClicked(actionEvent)
    openButtonCLicked()
    saveAllButtonClicked()
    helpMenuButtonClicked()
    valueEditChange()
    serialNumberEditChange()
    nameEditChange()
}

class AddItems{
    value: SimpleStringProperty
    serialNumber: SimpleStringProperty
    itemName: SimpleStringProperty

    getValue()
    setValue()
    getSerialNumber()
    setSerialNumber()
    getName()
    setName()
}

class EditItems {
    removeItem()
    editValue()
    editName()
    editSerialNumber()
}

class SortItems{
    sortByValue()
    sortByName()
    sortBySerialNumber()
}

class SearchItem{
    searchByValue()
    searchByName()
    searchBySerialNumber()
}

class FileOptions{
    fc: FileChooser
    desktop: Desktop

    saveFile()
    saveAsTSV()
    saveAsHTML()
    saveAsJSON()
    openFile()
}

@enduml